name: oxoo
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+10

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  # admob_flutter: ^3.0.0
  # app_review: ^2.1.2+1
  built_value: ^8.4.1
  carousel_slider: ^4.1.1
  change_app_package_name: ^1.1.0
  chewie: ^1.3.5
  country_code_picker: ^3.0.0
  cupertino_icons: ^1.0.5
  dart_chromecast: ^0.3.3
  dio: ^4.0.6
  equatable: ^2.0.5
  firebase_auth: ^4.19.6
  firebase_core: ^2.29.0
  flick_video_player: ^0.5.0

  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.1
  flutter_downloader: ^1.8.4
  flutter_facebook_auth: ^4.4.1
  csslib: 0.17.0
  # flutter_mdns_plugin: ^0.0.3
  flutter_pagewise: ^2.0.4
  flutter_paypal: ^0.0.8
  flutter_share: ^2.0.0
  flutter_spinkit: ^5.1.0
  # flutter_stripe: ^2.4.0
  flutter_svg: ^0.22.0
  fluttertoast: ^8.0.9
  get_it: ^7.1.3
  get: ^4.6.5
  google_sign_in: ^5.4.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.5
  image_picker: ^0.8.6
  in_app_purchase: ^3.0.8
  onesignal_flutter: ^3.4.1
  package_info_plus: ^3.0.0
  wakelock: ^0.6.2
  permission_handler: ^10.1.0
  pinput: ^2.2.16
  provider: ^6.0.4
  razorpay_flutter: ^1.3.7
  shimmer: ^2.0.0
  sign_in_with_apple: ^4.1.0
  # stripe_checkout: ^0.1.0
  url_launcher: ^6.1.6
  video_player: ^2.7.2
  visibility_detector: ^0.3.3

  webview_flutter: ^2.1.1
  youtube_player_flutter: ^8.1.1
  animated_notch_bottom_bar: ^0.0.6
  curved_navigation_bar: ^1.0.3
  device_preview: ^1.0.0
  flutter_screenutil: ^5.6.0
  google_fonts: ^4.0.0
  animated_splash_screen: ^1.3.0
  another_flutter_splash_screen: ^1.2.0
dev_dependencies:
  build_runner: ^2.0.6
  flutter_launcher_icons: ^0.10.0
  change_app_package_name: ^1.1.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/android_launcher_icon.jpg"
  bloc_test: ^3.0.0

#analyzer: ^0.41.0
flutter:
  uses-material-design: true
  assets:
    - assets/splash_image.png
    - assets/logo.png
    - assets/android_launcher_icon.jpg
    - assets/drawer_icon/
    - assets/images/
    - assets/
    - assets/bottom_nav/
    - assets/images/ic_button_apple.png

  fonts:
    - family: Gill Sans MT Condensed
      fonts:
        - asset: assets/fonts/gilc.ttf
    - family: Sans Serif
      fonts:
        - asset: assets/fonts/arabotom.ttf
